# Generated by Django 6.0.7 on 2026-07-12 11:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1st-2026-2027', '1st Semester 2026-2027'), ('2nd-2026-2027', '2nd Semester 2026-2027'), ('summer-2027', 'Summer 2027')], max_length=20)),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tuition_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('misc_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('misc_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Account',
                'verbose_name_plural': 'Student Accounts',
                'db_table': 'student_accounts',
                'ordering': ['-term'],
                'unique_together': {('student', 'term')},
            },
        ),
        migrations.CreateModel(
            name='ExamPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('prelim', 'Preliminary Exam'), ('midterm', 'Midterm Exam'), ('prefinal', 'Pre-Final Exam'), ('final', 'Final Exam')], max_length=10)),
                ('required_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('manual_override', models.BooleanField(blank=True, default=None, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_permits', to='finance.studentaccount')),
            ],
            options={
                'verbose_name': 'Exam Permit',
                'verbose_name_plural': 'Exam Permits',
                'db_table': 'exam_permits',
                'ordering': ['account', 'exam_type'],
                'unique_together': {('account', 'exam_type')},
            },
        ),
    ]
