# Generated by Django 5.0.7 on 2026-07-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leadership_position',
            field=models.CharField(choices=[('regular', 'Regular'), ('department_head', 'Department Head'), ('principal', 'Principal'), ('president', 'President (EEMG)')], default='regular', help_text='Leadership title for Teacher/Organization accounts. Department Head, Principal, or President auto-grants Admin.', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Teacher'), ('organization', 'Organization (EEMG)'), ('staff', 'Staff'), ('admin', 'Administrator'), ('alumni', 'Alumni'), ('guest', 'Guest')], default='guest', max_length=20),
        ),
    ]
