# Generated by Django 5.0.7 on 2026-07-11 12:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('room_type', models.CharField(choices=[('classroom', 'Classroom'), ('laboratory', 'Laboratory'), ('lecture_hall', 'Lecture Hall'), ('conference', 'Conference Room'), ('auditorium', 'Auditorium'), ('library', 'Library Room'), ('other', 'Other')], default='classroom', max_length=20)),
                ('building', models.CharField(max_length=100)),
                ('floor', models.CharField(max_length=20)),
                ('capacity', models.PositiveSmallIntegerField(default=30)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_computers', models.BooleanField(default=False)),
                ('has_aircon', models.BooleanField(default=False)),
                ('has_whiteboard', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
                'ordering': ['building', 'floor', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., CS101, MATH201', max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('foundation', 'Foundation'), ('major', 'Major'), ('elective', 'Elective'), ('general', 'General Education')], default='general', max_length=20)),
                ('units', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('lecture_hours', models.PositiveSmallIntegerField(default=3)),
                ('lab_hours', models.PositiveSmallIntegerField(default=0)),
                ('department', models.CharField(choices=[('bscs', 'BSCS - Computer Science'), ('bsba', 'BSBA - Business Administration'), ('beed', 'BEED - Education'), ('bshm', 'BSHM - Hospitality Management'), ('hbmc', 'HBMC - Multimedia Communications'), ('general', 'General Education'), ('admin', 'Administration')], default='general', max_length=20)),
                ('semester_offered', models.CharField(choices=[('1st', 'First Semester'), ('2nd', 'Second Semester'), ('summer', 'Summer'), ('all', 'All Semesters')], default='all', max_length=10)),
                ('year_level', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='prerequisite_for', to='academics.course')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1st-2026-2027', '1st Semester 2026-2027'), ('2nd-2026-2027', '2nd Semester 2026-2027'), ('summer-2027', 'Summer 2027')], max_length=20)),
                ('section', models.CharField(help_text='e.g., A, B, C', max_length=10)),
                ('schedule', models.CharField(help_text='e.g., MWF 9:00-10:30', max_length=100)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('capacity', models.PositiveSmallIntegerField(default=40)),
                ('enrolled_count', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('waitlist', 'Waitlist')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='academics.course')),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'role': 'faculty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Offering',
                'verbose_name_plural': 'Course Offerings',
                'db_table': 'course_offerings',
                'ordering': ['course__code', 'section'],
                'unique_together': {('course', 'semester', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('dropped', 'Dropped'), ('withdrawn', 'Withdrawn'), ('completed', 'Completed')], default='enrolled', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('dropped_at', models.DateTimeField(blank=True, null=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='academics.courseoffering')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'db_table': 'enrollments',
                'unique_together': {('student', 'course_offering')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prelim_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('midterm_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('prefinal_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('computed_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade_equivalent', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('finalized', 'Finalized')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('is_incomplete', models.BooleanField(default=False)),
                ('is_dropped', models.BooleanField(default=False)),
                ('entered_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='academics.enrollment')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_entered', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('class', 'Class Session'), ('meeting', 'Meeting'), ('event', 'Event'), ('exam', 'Examination'), ('seminar', 'Seminar/Workshop'), ('practice', 'Practice/Rehearsal'), ('other', 'Other')], max_length=20)),
                ('purpose_description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('expected_attendees', models.PositiveSmallIntegerField(default=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reservations', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(limit_choices_to={'role__in': ['faculty', 'staff', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='room_reservations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='academics.room')),
            ],
            options={
                'verbose_name': 'Room Reservation',
                'verbose_name_plural': 'Room Reservations',
                'db_table': 'room_reservations',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
