# Generated by Django 6.0.7 on 2026-07-13 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Senator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, upload_to='senators/%Y/%m/')),
                ('position', models.CharField(choices=[('senate_president', 'Senate President'), ('deputy_speaker', 'Deputy Speaker'), ('senator', 'Senator'), ('secretary', 'Secretary')], default='senator', max_length=20)),
                ('department', models.CharField(blank=True, help_text='e.g. College of Computer Studies', max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('term', models.CharField(blank=True, help_text='e.g. 2026-2027', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Senator',
                'verbose_name_plural': 'Senators',
                'db_table': 'senators',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chairperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaired_committees', to='portal.senator')),
                ('members', models.ManyToManyField(blank=True, related_name='committees', to='portal.senator')),
            ],
            options={
                'verbose_name': 'Committee',
                'verbose_name_plural': 'Committees',
                'db_table': 'committees',
                'ordering': ['order', 'name'],
            },
        ),
    ]
