# Generated by Django 6.0.7 on 2026-07-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_senator_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or Facebook video link (e.g. https://youtu.be/xxxx or a Facebook video post URL).'),
        ),
    ]
