# Generated by Django 6.0.7 on 2026-07-30 11:55

import apps.portal.storage_backends
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_announcement_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, storage=apps.portal.storage_backends.get_attachment_storage, upload_to='announcements/attachments/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload your own video (mp4, mov, webm, or ogg) to play directly on the site, no YouTube/Facebook link needed. If both this and Video URL are set, this uploaded video takes priority.', storage=apps.portal.storage_backends.get_video_storage, upload_to='announcements/videos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm', 'ogg'])]),
        ),
    ]
